[project]
name = "cse5914"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.2",
    "pycryptodome>=3.23.0",
    "supabase>=2.27.2",
]
